##Predicting the winner of the Premiere League matches (Football)

In this notebook I'm going to predict who's going to win each football match in the English Premier League using a machine learning model called `a Random Forest`

The notebook will include: 

*   Loading and cleaning data with Pandas libraru
*   Apply a machine learning model
*   Measuring how well this algorithm really works
*   Improve the algorithm
*   Getting some results

In [2]:
# Installing pandas library

import pandas as pd

# Reading in the initial data

matches = pd.read_csv("https://raw.githubusercontent.com/dataquestio/project-walkthroughs/master/football_matches/matches.csv", index_col=0)

In [3]:
# Looking for the first 6 rows of data

matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [4]:
#the DataFrame is made up of 1389 rows and 27 columns of data

matches.shape

(1389, 27)

In [5]:
38 * 20 * 2 #In the English Premier League, there are 20 teams, and each team plays 38 matches; data for two seasons

1520

In [6]:
#How many matches we had for each team in df

matches["team"].value_counts()

Southampton                 72
Brighton and Hove Albion    72
Manchester United           72
West Ham United             72
Newcastle United            72
Burnley                     71
Leeds United                71
Crystal Palace              71
Manchester City             71
Wolverhampton Wanderers     71
Tottenham Hotspur           71
Arsenal                     71
Leicester City              70
Chelsea                     70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: team, dtype: int64

In [7]:
#All Liverpool games in DataFrame

matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,Leeds United,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,Chelsea,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,Arsenal,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,Aston Villa,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,Everton,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,West Ham,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,Leicester City,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,Brighton,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,Wolves,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,Fulham,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,Tottenham,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,Crystal Palace,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,West Brom,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,Newcastle Utd,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,Southampton,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,Manchester Utd,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,Burnley,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,Tottenham,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,West Ham,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,Brighton,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,Manchester City,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,Leicester City,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,Everton,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,Chelsea,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,Fulham,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,Wolves,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,Arsenal,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,Leeds United,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,Newcastle Utd,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,Southampton,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,Manchester Utd,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,West Brom,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [8]:
#Looking how many matches were in every matchweek for 2 seasons 

matches["round"].value_counts()

Matchweek 1     39
Matchweek 16    39
Matchweek 34    39
Matchweek 32    39
Matchweek 31    39
Matchweek 29    39
Matchweek 28    39
Matchweek 26    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 2     39
Matchweek 19    39
Matchweek 17    39
Matchweek 20    39
Matchweek 15    39
Matchweek 5     39
Matchweek 3     39
Matchweek 13    39
Matchweek 12    39
Matchweek 4     39
Matchweek 11    39
Matchweek 10    39
Matchweek 9     39
Matchweek 8     39
Matchweek 14    39
Matchweek 7     39
Matchweek 6     39
Matchweek 30    37
Matchweek 27    37
Matchweek 22    37
Matchweek 21    37
Matchweek 18    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: round, dtype: int64

In [9]:
#Types of data

matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [11]:
#Convert data into datetime type (Algoithm can't work with data that is not numeric)

matches["date"] = pd.to_datetime(matches["date"])
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")
matches["day_code"] = matches["date"].dt.dayofweek
matches["result"] = (matches["result"] == "w").astype("int")

Creating predictors (#Predictors that converting datatype into numbers(int))

In [12]:
#Updated data

matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,0,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,0,18,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,0,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,1,15,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,0,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,0,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,1,0,10,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,0,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,0,1,17,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,0,0.0,4.0,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,0,18,19,6
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,0,0.0,2.0,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,0,1,6,15,5
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,0,1.0,0.0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,1,0,7,19,6
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,0,0.0,1.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,0,14,18,2
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,0,1.0,0.0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,1,4,16,6

In [10]:
#Setting up a target for machine learning model. The target is whether the team win or not

matches["target"] = (matches["result"] == "W").astype("int")

In [13]:
#Importing Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

In [14]:
#Initialazing RandomForestClassifier

rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [15]:
#Creating date type data for training

train = matches[matches["date"] < '2022-01-01']

In [16]:
#Declaring the test dataset

test = matches[matches["date"] > '2022-01-01']

In [17]:
#Creating a variable with a list with predictors

predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [18]:
#Fitting Random Forest model for predicting the target using trained predictors 

rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [19]:
#Generating predictions using predict methods

preds = rf.predict(test[predictors])

In [20]:
#Import accuracy_score what would tell what percentage of the time prediction is accurate

from sklearn.metrics import accuracy_score

In [21]:
error = accuracy_score(test["target"], preds)

In [22]:
#Looking for an accuracy

error

0.6123188405797102

In [23]:
#Creating a DataFrame which will combine actual and predicted values

combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [24]:
#Creating a two-way table that will show when predicted zero or one actually happened 

pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          141  31
1           76  28

In [25]:
#Import a metric that tells what percentage of time did the team actually win

from sklearn.metrics import precision_score

In [26]:
precision_score(test["target"], preds)

0.4745762711864407

In [27]:
#Split matches df up by team for computing team averages for team perfomance. Creating one df for every squad in data

grouped_matches = matches.groupby("team")

In [28]:
#All matches with Manchester City

group = grouped_matches.get_group("Manchester City").sort_values("date")

In [46]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2020-09-21,20:15,Premier League,Matchweek 2,Mon,Away,0,3.0,1.0,Wolves,...,2.0,1.0,1.0,2021,Manchester City,1,0,22,20,0
2,2020-09-27,16:30,Premier League,Matchweek 3,Sun,Home,0,2.0,5.0,Leicester City,...,1.0,0.0,0.0,2021,Manchester City,0,1,10,16,6
4,2020-10-03,17:30,Premier League,Matchweek 4,Sat,Away,0,1.0,1.0,Leeds United,...,1.0,0.0,0.0,2021,Manchester City,0,0,9,17,5
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,0,1.0,0.0,Arsenal,...,0.0,0.0,0.0,2021,Manchester City,1,1,0,17,5
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,0,1.0,1.0,West Ham,...,1.0,0.0,0.0,2021,Manchester City,0,0,21,12,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,0,0.0,0.0,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,0,0,6,20,0
44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,0,2.0,0.0,Burnley,...,0.0,0.0,0.0,2022,Manchester City,1,0,4,15,5
46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,0,2.0,2.0,Liverpool,...,1.0,0.0,0.0,2022,Manchester City,0,1,11,16,6
49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,0,3.0,0.0,Brighton,...,0.0,0.0,0.0,2022,Manchester City,1,1,3,20,2
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,0,5.0,1.0,Watford,...,0.0,1.0,1.0,2022,Manchester City,1,1,19,15,5

In [47]:
#Taking a group in, set of columns what we want to compute rolling averages for and then it'll take a set of new columns that we want to assign the rolling averages

def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [48]:
#Taking columns for computing rolling averages 

cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]

#Adding rolling part to the column
new_cols = [f"{c}_rolling" for c in cols]

In [49]:
#Calling rolling_averages for a single group

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,0,1.0,0.0,Arsenal,...,17,5,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,0,1.0,1.0,West Ham,...,12,5,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,0,1.0,0.0,Sheffield Utd,...,12,5,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,0,1.0,1.0,Liverpool,...,16,6,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,0,0.0,2.0,Tottenham,...,17,5,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,0,0.0,0.0,Crystal Palace,...,20,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,0,2.0,0.0,Burnley,...,15,5,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,0,2.0,2.0,Liverpool,...,16,6,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,0,3.0,0.0,Brighton,...,20,2,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,0,5.0,1.0,Watford,...,15,5,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [32]:
#Applying on function to each team essentialy

matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 32 2022-03-13  14:00  Premier League  Matchweek 29
                        33 2022-03-18  20:00  Premier League  Matchweek 30
                        34 2022-04-02  15:00  Premier League  Matchweek 31
                        35 2022-04-08  20:00  Premier League  Matchweek 32
                        36 2022-04-24  14:00  Premier League  Matchweek 34

                            day venue  result   gf   ga         opponent  ...  \
team                                                                      ...
Arsenal                 6   Sun  Home       0  2.0  1.0    Sheffield Utd  ...
                        7   Sat  Away       0  0.0  1.0  Manchester City  ...
                        9   Sun  Home       0  0.0  1.0   Leicester City  ...
                        11  Sun  Away       0  1.0  0.0   Manchester Utd  ...
                        13  Sun  Home       0  0.0  3.0      Aston Villa  ...
...                         ...   ...     ...  ...  ...              ...  ...
Wolverhampton Wanderers 32  Sun  Away       0  1.0  0.0          Everton  ...
                        33  Fri  Home       0  2.0  3.0     Leeds United  ...
                        34  Sat  Home       0  2.0  1.0      Aston Villa  ...
                        35  Fri  Away       0  0.0  1.0    Newcastle Utd  ...
                        36  Sun  Away       0  0.0  1.0          Burnley  ...

                            hour  day_code  gf_rolling  ga_rolling sh_rolling  \
team
Arsenal                 6     14         6    2.000000    1.333333   7.666667
                        7     17         5    1.666667    1.666667   5.333333
                        9     19         6    1.000000    1.666667   7.000000
                        11    16         6    0.666667    1.000000   9.666667
                        13    19         6    0.333333    0.666667   9.666667
...                          ...       ...         ...         ...        ...
Wolverhampton Wanderers 32    14         6    1.333333    1.000000  12.333333
                        33    20         4    1.666667    0.666667  12.333333
                        34    15         5    2.333333    1.000000  13.000000
                        35    20         4    1.666667    1.333333  13.000000
                        36    14         6    1.333333    1.666667  10.000000

                           sot_rolling dist_rolling fk_rolling  pk_rolling  \
team
Arsenal                 6     3.666667    14.733333   0.666667    0.000000
                        7     3.666667    15.766667   0.000000    0.000000
                        9     3.666667    16.733333   0.666667    0.000000
                        11    4.000000    16.033333   1.000000    0.000000
                        13    2.666667    18.033333   1.000000    0.333333
...                                ...          ...        ...         ...
Wolverhampton Wanderers 32    3.666667    19.300000   0.000000    0.000000
                        33    4.333333    19.600000   0.000000    0.000000
                        34    5.333333    19.833333   0.000000    0.000000
                        35    5.000000    18.533333   0.000000    0.000000
                        36    4.666667    17.633333   0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 6        0.000000
                        7        0.000000
                        9        0.000000
                        11       0.000000
                        13       0.333333
...                                   ...
Wolverhampton Wanderers 32       0.000000
                        33       0.000000
                        34       0.000000
                        35       0.000000
                        36       0.000000

[1317 rows x 40 columns]

In [33]:
#Drop extra index level

matches_rolling = matches_rolling.droplevel('team')
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,0,2.0,1.0,Sheffield Utd,...,14,6,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,0,0.0,1.0,Manchester City,...,17,5,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,0,0.0,1.0,Leicester City,...,19,6,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,0,1.0,0.0,Manchester Utd,...,16,6,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,0,0.0,3.0,Aston Villa,...,19,6,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,0,1.0,0.0,Everton,...,14,6,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
33,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,0,2.0,3.0,Leeds United,...,20,4,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
34,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,0,2.0,1.0,Aston Villa,...,15,5,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
35,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,0,0.0,1.0,Newcastle Utd,...,20,4,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,0,0.0,1.0,Burnley,...,14,6,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [34]:
#Assign values from zero to 1316 (we did unique values for each index)

matches_rolling.index = range(matches_rolling.shape[0])

In [35]:
#Creating a function what will help to make predictions easier (it includes all written code but in one function)

def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [36]:
#Adding new predictior what we created

combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [37]:
#Looking for an error. It is better now 

error

0.625

In [38]:
#We can see where misprediction exactly are 

combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [39]:
combined.head(10)

    actual  predicted       date     team        opponent  result
55       0          0 2022-01-23  Arsenal         Burnley       0
56       1          0 2022-02-10  Arsenal          Wolves       0
57       1          0 2022-02-19  Arsenal       Brentford       0
58       1          1 2022-02-24  Arsenal          Wolves       0
59       1          1 2022-03-06  Arsenal         Watford       0
60       1          1 2022-03-13  Arsenal  Leicester City       0
61       0          1 2022-03-16  Arsenal       Liverpool       0
62       1          0 2022-03-19  Arsenal     Aston Villa       0
63       0          0 2022-04-04  Arsenal  Crystal Palace       0
64       0          0 2022-04-09  Arsenal        Brighton       0

In [50]:
#By using this class we can avoid any misunderstandings in names. Doing it by pandas map method

class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [43]:
#Using created class on dataframe

combined["new_team"] = combined["team"].map(mapping)

In [44]:
#Merging DataFrame with itself. I want to see if predictions match up on both sides 

merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,0,Arsenal,0,0,Burnley,Arsenal,0,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,0,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,0,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,0,Arsenal,0,0,Brentford,Arsenal,0,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,0,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,0,Wolves
4,1,1,2022-03-06,Arsenal,Watford,0,Arsenal,0,0,Watford,Arsenal,0,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,1,0,2022-03-13,Wolverhampton Wanderers,Everton,0,Wolves,0,0,Everton,Wolves,0,Everton
258,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,0,Wolves,1,0,Leeds United,Wolves,0,Leeds United
259,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,0,Wolves,0,0,Aston Villa,Wolves,0,Aston Villa
260,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,0,Wolves,1,0,Newcastle United,Wolves,0,Newcastle Utd
261,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,0,Wolves,1,0,Burnley,Wolves,0,Burnley

In [51]:
#Looking for all rows where one team predicted to win and other predicted to lose, it helps algorithm to be more confident in

merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    27
0    13
Name: actual_x, dtype: int64

In [52]:
#Accuracy is about 67%

27/40

0.675